In [2]:
import numpy as np

In [10]:
x = np.array([[0.2, 3.1, 1], [1.0, 3.0, 1], [-0.2, 1.2, 1], [1.0, 1.1, 1]])
w0 = np.array([[-1, 1, 0]]).T
y = np.array([[1, 1, 0, 0]]).T

In [28]:
def logFn(x, w):
    gamma = x.dot(w)
    gamma = np.exp(-gamma)
    result = np.empty(gamma.shape)
    for i in range(4):
        result[i][0] = 1/(1 + gamma[i][0])
    return result
s0 = logFn(x, w0)
print(s0)

[[0.94784644]
 [0.88079708]
 [0.80218389]
 [0.52497919]]


In [29]:
print(s0*(1-s0))
diagonal = np.diagflat(s0*(1-s0))
print(diagonal)

[[0.04943357]
 [0.10499359]
 [0.1586849 ]
 [0.24937604]]
[[0.04943357 0.         0.         0.        ]
 [0.         0.10499359 0.         0.        ]
 [0.         0.         0.1586849  0.        ]
 [0.         0.         0.         0.24937604]]


In [30]:
gradCost0 = np.dot(x.T, (y-s0))
print(gradCost0)
hessian0 = x.T.dot(diagonal).dot(x)
print(np.linalg.inv(hessian0))
w1 = w0 + np.linalg.inv(hessian0).dot(gradCost0)
print(w1)

[[-0.23490878]
 [-1.02081296]
 [-1.15580659]]
[[ 6.10355726 -0.45959808 -2.84586321]
 [-0.45959808  2.51714973 -3.90332816]
 [-2.84586321 -3.90332816  9.9343525 ]]
[[ 1.32465198]
 [ 3.04991697]
 [-6.82910388]]


In [31]:
s1 = logFn(x, w1)
print(s1)
diagonal = np.diagflat(s1*(1-s1))

[[0.94737826]
 [0.97455097]
 [0.03124556]
 [0.10437391]]


In [26]:
gradCost1 = np.dot(x.T, (y-s1))
hessian1 = x.T.dot(diagonal).dot(x)
w2 = w1 + np.linalg.inv(hessian1).dot(gradCost1)
print(w2)

[[ 1.36602464]
 [ 4.15753654]
 [-9.19961627]]
